name: "access-analyzer"

permissions:
  id-token: write
  contents: read

on:
  push:
    branches: ['main']
    paths:
      - 'access-analyzer/**'
  workflow_dispatch:
    inputs:
      apply:
        description: 'Apply changes after plan'
        required: false
        type: boolean
        default: false
      terraform_version:
        description: 'Terraform version to use'
        required: false
        type: string
        default: '1.5.7'
      aws_region:
        description: 'AWS region to use'
        required: false
        type: string
        default: 'us-west-1'
      oidc_role_arn:
        description: 'Optional AWS role ARN to assume via GitHub OIDC'
        required: false
        type: string
      role_session_name:
        description: 'Optional role session name for OIDC assume'
        required: false
        type: string
        default: ''

jobs:
  call-reusable:
    uses: ./.github/workflows/reusable.yml
    secrets:
      OIDC_ROLE_ARN: "arn:aws:iam::803103365620:oidc-provider/token.actions.githubusercontent.com"
      ROLE_SESSION_NAME: ${{ secrets.ROLE_SESSION_NAME }}
    with:
      tf_working_dir: access-analyzer
      aws_region: ${{ (github.event_name == 'workflow_dispatch' && github.event.inputs.aws_region) || 'us-west-1' }}
      terraform_version: ${{ (github.event_name == 'workflow_dispatch' && github.event.inputs.terraform_version) || '1.5.7' }}
      auto_apply: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.apply == 'true' }}

      # Optional import command
      pre_plan_commands: |
        # Attempt to import existing Access Analyzer
        terraform import "aws_accessanalyzer_analyzer.this[0]" winfo-org-access-analyzer || echo "Access Analyzer imported successfully"
