name: "ecr-scan"

on:
  push:
    branches: [ 'main' ]
    paths:
      - 'ecr-scan/**'
  workflow_dispatch:
    inputs:
      apply:
        description: 'Apply changes after plan'
        required: false
        default: false
        type: boolean
      terraform_version:
        description: 'Terraform version to use'
        required: false
        default: '1.5.7'
        type: string
      aws_region:
        description: 'AWS region to use'
        required: false
        default: 'us-east-1'
        type: string
      apply_environment:
        description: 'GitHub environment name to require approval before apply'
        required: false
        default: 'terraform-apply'
        type: string

jobs:
  call-reusable:
    uses: ./.github/workflows/terraform-reusable.yml
    with:
      tf_working_dir: ecr-scan
      aws_region: ${{ (github.event_name == 'workflow_dispatch' && github.event.inputs.aws_region) || 'us-east-1' }}
      terraform_version: ${{ (github.event_name == 'workflow_dispatch' && github.event.inputs.terraform_version) || '1.5.7' }}
      auto_apply: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.apply }}
      apply_environment: ${{ (github.event_name == 'workflow_dispatch' && github.event.inputs.apply_environment) || 'terraform-apply' }}
